### ISSUE TITLE
Small improvments

### ISSUE THREAD

**Issue by noamokman** [danielhusar/movie-title#1]
Hi there,
I'm using your package and I wanted to add a small changes to handle some problems.
I tried it on 67 movies and these were the problem ones.
(file name and then the resolved name)

```
stratos-boyhood.720p.mkv
stratos-boyhood.720p

avchd-exam.2009.720p.mkv
avchd-exam

Requiem.For.A.Dream.DIRECTORS.CUT.2000.720p.BrRip.x264.YIFY.mp4
Requiem For A Dream DIRECTORS CUT

blow-this.is.where.i.leave.you.2014.1080p.bluray.x264.mkv
blow-this is where i leave you

snow-white.bird.in.a.blizzard.2014.limited.720p.bluray.x264.mkv
snow-white bird in a blizzard
```

Looks like:
- Some distributions like to place the name at the start with a hyphen.
- `DIRECTORS CUT` could be blacklisted.
- If the year isn't specified the resolution remains.

Would you like a PR?

**Comment by danielhusar** [comment]
Hey,

of course, feel free to submit PR.

Thanks.
